server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/le_exam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: 15550310405@163.com
    password: BEVFUCPTGZJJQFTK
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapperxml/*.xml

web:
  upload-path: C:/Users/DKT/Desktop/images/
